# Autogenerated wrapper script for Jinja2Cpp_jll for aarch64-apple-darwin
export libjinja2cpp

using boost_jll
JLLWrappers.@generate_wrapper_header("Jinja2Cpp")
JLLWrappers.@declare_library_product(libjinja2cpp, "@rpath/libjinja2cpp.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(boost_jll)
    JLLWrappers.@init_library_product(
        libjinja2cpp,
        "lib/libjinja2cpp.1.3.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
